### ISSUE TITLE
Pull-Down Menu Not Responsive

### ISSUE THREAD

**Issue by iantga** [WOEIP/truck-tracker#20]
The pull-down menu to move between the app's sections isn't responsive on mobile phones. Doesn't work most of the time.
![Menu Section Pull_down menu bug](https://user-images.githubusercontent.com/48457911/54499143-c314ec00-48cb-11e9-9ff2-9678a6128037.jpg)

**Comment by motching** [comment]
@iantga Currently I'm not able to reproduce the issue. What phone and OS version were you checking? Is there a specific way the bug can be triggered?

**Comment by iantga** [comment]
The phone was an iPhone 8 and I just tested it on my current OS version (12.2) and it doesn't work (experienced it on the previous version as well). I am unsure if there are specific ways to trigger it, however I always experience said issue. It may be only on my phone however.

**Comment by iantga** [comment]
Additionally, I'll test out on other people's phones if they are having the same issue.

**Comment by motching** [comment]
Ok, I got to try it on an iphone and I indeed saw it not working. Weird. I'll track it down!

**Comment by motching** [comment]
@iantga I don't have an iphone at hand at the moment but I might have found a fix. It's a shot in the dark, I think it has a 50% chance to work :D

'Fix' is deployed, please check and let me know. If it's still buggy I can fix it on Wednesday when I'll be home, I can use my wife's phone.

**Comment by iantga** [comment]
It works perfectly!

**Comment by motching** [comment]
thanks, closing
