### ISSUE TITLE
DB access generic

### ISSUE THREAD

**Issue by motching** [WOEIP/truck-tracker#30]
Right now the DB access uses my password
  * change the PW
  * create a little doc

**Comment by motching** [comment]
Talked to Joe to pick his brain. We'll have different users:
  * DB Admin user with all the rights
  * Admin user with write rights
  * App user with write rights
  * Read user for displaying the data without login

https://tableplus.com/blog/2018/04/postgresql-how-to-grant-access-to-users.html

**Comment by theecrit** [comment]
What's the functional difference between the Admin and App users? 

For what it's worth, WOAQ's user roles and permissions are [mapped here](https://docs.google.com/spreadsheets/d/1lfJVD3IqZpYeQr86rmdTuW4ASYuEpec5l7o0WiH6SZc/edit?usp=sharing). The two MVP roles are SysAdmin and Anon, and permissions are limited based on the functionality built into the MVP. The full [account management project is here](https://github.com/openoakland/woeip/projects/6).
