### ISSUE TITLE
Improve confirmation of user registration

### ISSUE THREAD

**Issue by theecrit** [WOEIP/truck-tracker#57]
## Description

Current experience doesn't provide clear confirmation that account registration has been submitted. User clicks "submit" and while the button state changes, there's no messaging to confirm submission and the user's info remains visible in the form fields.  

<img src="https://user-images.githubusercontent.com/32755410/102022832-374d1f80-3d3e-11eb-8b55-1253f832f94b.PNG" width="250px">

## Proposed solution

- Remove form fields on submit
- Add a confirmation that explains what will happen next ("Thank you! Your information will be reviewed by our team and we'll send you an email when your account has been activated. If you have questions, you can email info@woeip.org."

**Comment by theecrit** [comment]
[
![Uploading IMG_9524.PNG…]()
](url)

**Comment by Ajay-Vishwanath** [comment]
@theecrit I think with the current user account flow - after registration a user account is automatically activated and is able to make reports. In the future, maybe this would change where their active status is by default `inactive` upon registration, and only when that is changed will they be able to make reports. 

For now is this an okay message?

"Thank you! Your account has been activated and you are now able to make TruckTracker reports. If you have any questions you can email info@woeip.org"

**Comment by motching** [comment]
Done by Ajay!
