### ISSUE TITLE
DOT number

### ISSUE THREAD

**Issue by motching** [WOEIP/truck-tracker#59]
We need the DOT number because that's what uniquely identifies the truck and the owner. It's always on the driver side door.

Add an optional(?) field for the number AND educate the users to take a photo of the driver side door.

**Comment by theecrit** [comment]
Related to #58

**Comment by theecrit** [comment]
Text field: 

- Label: What is the truck's DOT number?
- Help text: The DOT number is a series of numbers and letters, usually on the driver's side door of the truck.
