### ISSUE TITLE
[Enhancement] Add bug reporting to comment form

### ISSUE THREAD

**Issue by theecrit** [WOEIP/truck-tracker#76]
## Description

We'd like to use the current [contact form](https://trucktracker.net/?#contact) to encourage bug reports/feedback.

### Proposed solution

There are a couple of different approaches we could take, depending on how complex we want to get:
1. ~Allow user to select from a list of feedback types that displays a specific set of fields based on their selection.~
**2. Display all fields at once, and use clear headers/subheads to help the user know which fields to fill out.**

Option 1 allows for more precision, particularly when taking bug reports. Option 2 is clunkier for the user but much easier to implement.

Note some additional suggested changes in the wireframes, regardless of approach used:

- Changed page title to match nav menu terminology (helps users know they're in the right place)
- Updated intro text to include actual contact for WOEIP (similar to their main contact page)
- Added an "Are you local?" question to the form (will require a database update to record this info, but will be helpful for verification and general impact measurement, without being too invasive—will confirm with Brian)
- Provided guidance for the confirmation messaging.

### Adjustments

- Add captcha to contact form
- Local question (required): "Do you live or work in West Oakland?" radio: yes/no (default: unselected on both)

#### Wireframes

![TruckTracker-wireframes-Contact-20210113](https://user-images.githubusercontent.com/32755410/104529327-50a3ee80-55be-11eb-92aa-45ce16938808.png)

**Comment by Ajay-Vishwanath** [comment]
I implemented the single view wireframe in my last PR - just need to do something with that data now (configure the email automation) which is being held in state.

**Comment by theecrit** [comment]
- Selection added to form; needs to be hooked up to email

**Comment by motching** [comment]
Attila will implement sending the email

**Comment by motching** [comment]
I added the message relay, this should be good.

I send a test message to Brian, once he confirms he got it, I'll close this.

**Comment by motching** [comment]
Done
