### ISSUE TITLE
Account creation enhancements

### ISSUE THREAD

**Issue by theecrit** [WOEIP/truck-tracker#79]
## Auto-responder email

On registration submit:
- Confirm account registration to user
- Notification to Brian so he can validate

On user confirmation of registration
 - Welcome
 - Why TT?
 - WOEIP intro/link

Send emails from: trucktracker@woiep.org
- trucktracker@ forwards to Brian directly

## Registration form
- Add captcha

**Comment by theecrit** [comment]
Jess to review copy in emails

**Comment by motching** [comment]
Needs
 * testing the flow
 * email wording
 * captcha

**Comment by motching** [comment]
Captcha won't be done, see my email

**Comment by motching** [comment]
Seems done to me, closing
